export { AgitationSection } from './agitation-section'
export { SolutionSection } from './solution-section'
export { CredentialsSection } from './credentials-section'
export { GuaranteeSection } from './guarantee-section'
export { TestimonialsSection } from './testimonials-section'
export { UrgencyBanner, FloatingUrgency } from './urgency-banner'
export { SEOHead } from './seo-head'
export { ProductVSL } from './ProductVSL'
export { WhatsAppFloat } from '../marketing/WhatsAppFloat'
