/**
 * Marketing Prompts Module
 * Exports all marketing-related prompts
 */

export {
  CONTENT_AGENT_SYSTEM_PROMPT,
  INSTAGRAM_POST_PROMPT,
  LINKEDIN_POST_PROMPT,
  BLOG_ARTICLE_PROMPT,
  NEWSLETTER_PROMPT,
  VIDEO_SCRIPT_PROMPT,
  CONTENT_CALENDAR_PROMPT,
  TOPIC_IDEAS_PROMPT,
  REPURPOSE_CONTENT_PROMPT,
  LEGAL_AREA_CONTEXTS,
  getPromptForPlatform,
  getLegalAreaContext,
  buildContentPrompt,
} from './content-prompts'

export {
  SOCIAL_AGENT_SYSTEM_PROMPT,
  COMMENT_RESPONSE_PROMPT,
  ENGAGEMENT_ANALYSIS_PROMPT,
  SCHEDULE_OPTIMIZATION_PROMPT,
  HASHTAG_STRATEGY_PROMPT,
  INSTAGRAM_OPTIMIZATION_PROMPT,
  LINKEDIN_OPTIMIZATION_PROMPT,
  getOptimalTimes,
  getHashtagLimits,
  isOptimalTime,
} from './social-prompts'

export {
  ADS_AGENT_SYSTEM_PROMPT,
  GOOGLE_ADS_CAMPAIGN_PROMPT,
  META_ADS_CAMPAIGN_PROMPT,
  CAMPAIGN_OPTIMIZATION_PROMPT,
  KEYWORD_ANALYSIS_PROMPT,
  AD_COPY_OPTIMIZATION_PROMPT,
  AUDIENCE_ANALYSIS_PROMPT,
  BUDGET_ALLOCATION_PROMPT,
  WEEKLY_ADS_REPORT_PROMPT,
  LEAD_QUALITY_ANALYSIS_PROMPT,
  getLegalAdsBenchmarks,
  getRecommendedKeywords,
  getNegativeKeywords,
  getAdCharacterLimits,
} from './ads-prompts'

export {
  SEO_AGENT_SYSTEM_PROMPT,
  KEYWORD_RESEARCH_PROMPT,
  CONTENT_GAP_ANALYSIS_PROMPT,
  PAGE_OPTIMIZATION_PROMPT,
  CONTENT_BRIEF_PROMPT,
  TECHNICAL_AUDIT_PROMPT,
  SITE_ARCHITECTURE_PROMPT,
  LOCAL_SEO_AUDIT_PROMPT,
  BACKLINK_ANALYSIS_PROMPT,
  LINK_BUILDING_STRATEGY_PROMPT,
  SEO_MONTHLY_REPORT_PROMPT,
  getSEOBenchmarks,
  getPrimaryKeywords,
  getLegalSchemaTypes,
  calculateContentScore,
} from './seo-prompts'

export {
  VIDEO_AGENT_SYSTEM_PROMPT,
  REELS_SCRIPT_PROMPT,
  YOUTUBE_SCRIPT_PROMPT,
  WEBINAR_SCRIPT_PROMPT,
  STORIES_SCRIPT_PROMPT,
  TESTIMONIAL_SCRIPT_PROMPT,
  VIDEO_SEO_PROMPT,
  CONTENT_REPURPOSE_PROMPT,
  VIDEO_SERIES_PROMPT,
  CONTENT_CALENDAR_VIDEO_PROMPT,
  getOptimalDuration,
  getVideoSpecs,
  getHookTemplates,
  getCTATemplates,
} from './video-prompts'

export {
  DESIGN_AGENT_SYSTEM_PROMPT,
  INSTAGRAM_POST_DESIGN_PROMPT,
  LINKEDIN_POST_DESIGN_PROMPT,
  STORIES_DESIGN_PROMPT,
  THUMBNAIL_DESIGN_PROMPT,
  EBOOK_COVER_PROMPT,
  INFOGRAPHIC_DESIGN_PROMPT,
  BRAND_TEMPLATE_PROMPT,
  PRESENTATION_TEMPLATE_PROMPT,
  getBrandColors,
  getFontPairings,
  getPlatformDimensions,
  getLegalIcons,
  getImageStyleGuide,
} from './design-prompts'
