/**
 * Executive Prompts Module
 * Exports all executive-level prompts
 */

// CEO Prompts
export {
  CEO_AGENT_SYSTEM_PROMPT,
  DAILY_BRIEFING_PROMPT,
  STRATEGIC_DECISION_PROMPT,
  RESOURCE_ALLOCATION_PROMPT,
  PRIORITY_MATRIX_PROMPT,
  AGENT_COORDINATION_PROMPT,
  ESCALATION_HANDLING_PROMPT,
  WEEKLY_EXECUTIVE_REPORT_PROMPT,
  MONTHLY_STRATEGIC_REVIEW_PROMPT,
  getApprovalLevel,
  calculatePriorityScore,
  getStrategicKPIs,
  determineEscalationSeverity,
} from './ceo-prompts'

// CMO Prompts
export {
  CMO_AGENT_SYSTEM_PROMPT,
  MARKETING_STRATEGY_PROMPT,
  BUDGET_ALLOCATION_PROMPT,
  CONTENT_CALENDAR_COORDINATION_PROMPT,
  CAMPAIGN_COORDINATION_PROMPT,
  CHANNEL_PERFORMANCE_PROMPT,
  MARKETING_ROI_PROMPT,
  WEEKLY_MARKETING_REPORT_PROMPT,
  calculateChannelEfficiency,
  getChannelsByObjective,
  getRecommendedContentMix,
} from './cmo-prompts'

// COO Prompts
export {
  COO_AGENT_SYSTEM_PROMPT,
  OPERATIONS_DASHBOARD_PROMPT,
  CAPACITY_PLANNING_PROMPT,
  PROCESS_OPTIMIZATION_PROMPT,
  QUALITY_METRICS_PROMPT,
  INCIDENT_ANALYSIS_PROMPT,
  AGENT_WORKLOAD_PROMPT,
  DAILY_OPERATIONS_REPORT_PROMPT,
  WEEKLY_OPERATIONS_REPORT_PROMPT,
  calculateOperationalHealth,
  getSLADefinitions,
  getEscalationLevels,
} from './coo-prompts'

// CFO Prompts
export {
  CFO_AGENT_SYSTEM_PROMPT,
  CASH_FLOW_ANALYSIS_PROMPT,
  RECEIVABLES_ANALYSIS_PROMPT,
  DRE_ANALYSIS_PROMPT,
  BUDGET_VS_ACTUAL_PROMPT,
  REVENUE_ANALYSIS_PROMPT,
  PROFITABILITY_ANALYSIS_PROMPT,
  FINANCIAL_FORECAST_PROMPT,
  WEEKLY_FINANCIAL_REPORT_PROMPT,
  MONTHLY_FINANCIAL_REPORT_PROMPT,
  calculateFinancialHealth,
  getExpenseCategories,
  getRevenueCategories,
  formatCurrency,
} from './cfo-prompts'
